language: node_js
node_js:
  - 0.8
  - 0.10
before_install: npm install -g npm@~1.4.6
after_script: ./node_modules/.bin/istanbul cover ./node_modules/mocha/bin/_mocha test/core --report lcovonly -- -R spec && cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js --verbose
sudo: false